name: Build

on:
  push:
    branches: [ master, beta, v1.2.12, v1.3.15, test-workflow ]
    tags: [ release-v*, release-b*, release-e* ]
  pull_request:
    branches: [ master, beta, v1.2.12 ]
    types: [ review_requested, ready_for_review ]
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Initialize submodules
        uses: snickerbockers/submodules-init@v4

      - name: Read tag name
        uses: olegtarasov/get-tag@v2.1.1
        id: tagName

      - name: Read configuration file
        id: dotenv
        uses: falti/dotenv-action@v0.2.8
        with:
          path: .github/resources/config.env
          log-variables: true

      - name: Set environment variables
        run: |
          echo "ARTIFACT_NAME=Enhanced Battle Test ${{steps.dotenv.outputs.mod_version}} for Bannerlord ${{steps.dotenv.outputs.game_version}}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup .NET Core 2.2.x
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '2.2.x'

      - name: Setup .NET Core 6.0.x
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Download DepotDownloader 3.4.0
        uses: i3h/download-release-asset@v1.3.3
        with:
          owner: SteamRE
          repo: DepotDownloader
          tag: DepotDownloader_3.4.0
          file: DepotDownloader-windows-x64.zip

      - name: Extract DepotDownloader 3.4.0
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: DepotDownloader-windows-x64.zip
          pathTarget: depotdownloader

      - name: Download Bannerlord binaries
        env:
          STEAM_USERNAME: ${{secrets.STEAM_LOGIN}}
          STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        run: |
          depotdownloader/DepotDownloader.exe -app 261550 -depot 261551 -branch ${{steps.dotenv.outputs.game_branch}} -username "$env:STEAM_USERNAME" -password "$env:STEAM_PASSWORD" -filelist ./.github/resources/FileFilters.regexp -dir bannerlord
          depotdownloader/DepotDownloader.exe -app 261550 -depot 261552 -branch ${{steps.dotenv.outputs.game_branch}} -username "$env:STEAM_USERNAME" -password "$env:STEAM_PASSWORD" -filelist ./.github/resources/FileFilters.regexp -dir bannerlord

      - name: Build solution
        run: |
          nuget restore .\source\EnhancedBattleTest.sln
          MSBuild.exe .\source\EnhancedBattleTest.sln /p:Configuration=Release /p:GamePath="$PWD\bannerlord\"

      - name: Generate HTML files
        run: |
          dotnet md2html -i ..\..\README.md -o ..\package\EnhancedBattleTest\README.html
          dotnet md2html -i ..\..\README.zh-CN.md -o ..\package\EnhancedBattleTest\README.zh-CN.html
          dotnet md2html -i ..\..\CHANGELOG.md -o ..\package\EnhancedBattleTest\CHANGELOG.html
        working-directory: .\source\EnhancedBattleTest\

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}} ${{steps.dotenv.outputs.game_branch}}
          path: .\source\package\*

      - name: Zip output
        run: Compress-Archive -Path .\source\package\* -DestinationPath "${{env.ARTIFACT_NAME}}.zip"
        if: >-
          contains(github.ref, 'refs/tags/release-v') ||
          contains(github.ref, 'refs/tags/release-b') ||
          contains(github.ref, 'refs/tags/release-e')

      - name: Create release
        uses: ncipollo/release-action@v1.11.1
        if: >-
          contains(github.ref, 'refs/tags/release-v') ||
          contains(github.ref, 'refs/tags/release-b') ||
          contains(github.ref, 'refs/tags/release-e')
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: ${{env.ARTIFACT_NAME}}.zip
          name: Release ${{env.ARTIFACT_NAME}} ${{steps.dotenv.outputs.game_branch}}
          tag: ${{steps.tagName.outputs.tag}}
          artifactContentType: application/zip
